DROP TABLE CAR IF EXISTS;
DROP TABLE OPTIONS IF EXISTS;
DROP TABLE OPTION_SELECTED IF EXISTS;

CREATE TABLE CAR (
	id		INTEGER PRIMARY KEY NOT NULL,
	make	VARCHAR,
	model	VARCHAR,
	edition	VARCHAR,
	price	DECIMAL	
);

CREATE TABLE OPTIONS (
	id		INTEGER PRIMARY KEY NOT NULL,
	name	VARCHAR
);

CREATE TABLE OPTION_SELECTED (
	car_id	INTEGER,
	opt_id	INTEGER,
	price	DECIMAL
);
