DROP TABLE OPTION_SELECTED IF EXISTS;
DROP TABLE CAR IF EXISTS;
DROP TABLE OPTIONS IF EXISTS;


CREATE TABLE CAR (
	id		INTEGER PRIMARY KEY NOT NULL,
	make	VARCHAR,
	model	VARCHAR,
	edition	VARCHAR,
	price	INTEGER	
);

CREATE TABLE OPTIONS (
	id		INTEGER PRIMARY KEY NOT NULL,
	name	VARCHAR
);

CREATE TABLE OPTION_SELECTED (
	id		INTEGER PRIMARY KEY NOT NULL,
	car_id	INTEGER,
	opt_id	INTEGER,
	price	INTEGER
);
